### ISSUE TITLE
Sample flow not working

### ISSUE THREAD

**Issue by jeff-bonevich** [julien-pal/node-red-contrib-grpc#14]
I've installed the nodes into a locally running Node-Red install (v 1.2.9 on a MacBookPro running Catalina 10.15.7) and imported the sample flow but cannot get it to work. Trying the "User1 joins" flow, I see an error in debug window: 

{"_msgid":"13b1a98f.d1bcf6","payload":{"user":"User1","text":"Hello"},"topic":"","error":"Error: 12 UNIMPLEMENTED: The server does not implement the method /example.Chat/join"}

![image](https://user-images.githubusercontent.com/55404184/113932573-c4225a00-97c1-11eb-9d88-cd82ac239994.png)

Any assistance would be appreciated!

**Comment by jeff-bonevich** [comment]
Looking closer, the sample as provided does not work.  "Call join chat" is a normal grpc-call node, but is calling a streaming method ("rpc join(stream Message) returns (stream Message){}") and therefore is not actually delivering anything as msg.payload to "Join chat" method implementation.  Instead "Join chat" gprc-register-function must be changed to the joinMono method.  I will attach an updated example flow when I finish fixing this one.

**Comment by namgk** [comment]
Thanks for looking Jeff, I haven't used any of the streaming feature of grpc so didn't know about this issue. A simple request/response protobuf works though.

**Comment by jeff-bonevich** [comment]
Agreed.  Here is a much simpler demo of it:

`[{"id":"382dc006.1c745","type":"tab","label":"Flow 4","disabled":false,"info":""},{"id":"3ba93c69.fabff4","type":"grpc-register-function","z":"382dc006.1c745","name":"sayHello","server":"8c8e26a0.4a01e8","service":"Hello","method":"sayHello","x":100,"y":80,"wires":[["fd1f689f.bd3e78"]]},{"id":"b590389d.0b5f18","type":"grpc-response","z":"382dc006.1c745","name":"","x":600,"y":80,"wires":[]},{"id":"fd1f689f.bd3e78","type":"function","z":"382dc006.1c745","name":"sayHello","func":"name = msg.payload.name\nmsg.payload = { \"message\": \"Hello \" + name + \"!\" }\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":320,"y":80,"wires":[["b590389d.0b5f18"]]},{"id":"f4d9fd8.d9123","type":"grpc-call","z":"382dc006.1c745","name":"","server":"61ff2500.2e1d6c","service":"Hello","method":"sayHello","chain":"","key":"","x":550,"y":220,"wires":[["aa08bd2b.97c5b"]]},{"id":"1b4bbcda.9255a3","type":"inject","z":"382dc006.1c745","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"str","x":100,"y":220,"wires":[["83f9083f.6e5248"]]},{"id":"aa08bd2b.97c5b","type":"debug","z":"382dc006.1c745","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":750,"y":220,"wires":[]},{"id":"83f9083f.6e5248","type":"function","z":"382dc006.1c745","name":"supply name","func":"msg.payload = {name: \"YOU\"}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":300,"y":220,"wires":[["f4d9fd8.d9123"]]},{"id":"8c8e26a0.4a01e8","type":"grpc-server","port":"50081","name":"LocalHelloWorldRPC","server":"","protoFile":"syntax = \"proto3\";\n\npackage example;\n\nservice Hello {\n  rpc sayHello (HelloRequest) returns (HelloResponse) {}\n}\n\nmessage HelloRequest {\n  string name = 1;\n}\n\nmessage HelloResponse {\n  string message = 1;\n}\n","ca":"","chain":"","key":"","mutualTls":false,"localServer":true},{"id":"61ff2500.2e1d6c","type":"grpc-server","port":"50081","name":"RemoteHelloWorldRPC","server":"","protoFile":"syntax = \"proto3\";\n\npackage example;\n\nservice Hello {\n  rpc sayHello (HelloRequest) returns (HelloResponse) {}\n}\n\nmessage HelloRequest {\n  string name = 1;\n}\n\nmessage HelloResponse {\n  string message = 1;\n}\n","ca":"","chain":"","key":"","mutualTls":false,"localServer":false}]`

**Comment by jeff-bonevich** [comment]
Sorry for the messy code block.  Here it is attached as a file.
[simple-grpc.txt](https://github.com/julien-pal/node-red-contrib-grpc/files/6280998/simple-grpc.txt)

**Comment by namgk** [comment]
Thanks again Jeff, I just updated the Readme. Close now.
