### ISSUE TITLE
Node-RED flow examples

### ISSUE THREAD

**Issue by tmdoit-zz** [julien-pal/node-red-contrib-grpc#2]
Hi,
great contribution! Will be very helpful if you add some simple flow examples for a quick start.

**Comment by julien-pal** [comment]
Hi ! 
I have uploaded an example of a chat using the grpc nodes on NodeRed.
You can find it [here](https://flows.nodered.org/flow/9b5dee7e39a71bc3b19ac669be0479e5)

I hope it will help.

**Comment by jeff-bonevich** [comment]
Could you please include the link above on the main page, so that noobs like me have a chance to find an example of using the nodes?  Thanks!

**Comment by namgk** [comment]
done
