### ISSUE TITLE
Method not exists due to incorrect variable name

### ISSUE THREAD

**Issue by AitorF** [julien-pal/node-red-contrib-grpc#3]
`grpc-call.js:15` uses `methode` variable name instead the correct `method` name, resulting in 

> Method  not in proto file

error.

**Comment by julien-pal** [comment]
Thanks for the heads up.
I have fixed the issue in the commit [6c918264bba1ede3eda5b599a47fa39344be6c82](https://github.com/julien-pal/node-red-contrib-grpc/commit/6c918264bba1ede3eda5b599a47fa39344be6c82)
